site_name: Bitcoin Physics

site_url: http://0.0.0.0:8000

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
- Home: README.md
- Economic Energy: EconomicPotential.md
- Bitcoin Entropy: BitcoinEntropy.md
- WorkLog: WorkLog.md

theme:
  name: material

plugins:
  - search

markdown_extensions:
  - admonition
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs
